language: elixir

script: mix ci

matrix:
  include:
    - elixir: '1.8.1'
      otp_release: '21.3.8'
    - elixir: '1.9.0'
      otp_release: '22.0.1'

cache:
  directories:
    - _build
    - deps
