language: elixir

script:
  - mix format --check-formatted
  - mix credo --strict
  - travis_wait 30 mix dialyzer
  - mix coveralls.travis

matrix:
  include:
    - elixir: "1.8.1"
      otp_release: "21.3.8"
    - elixir: "1.9.0"
      otp_release: "22.0.1"
    - elixir: "1.10.4"
      otp_release: "22.0.1"
    - elixir: "1.10.4"
      otp_release: "23.0.1"
    - elixir: "1.11.4"
      otp_release: "23.2.5"
    - elixir: "1.12.0"
      otp_release: "24.0.1"
    - elixir: "1.14.0"
      otp_release: "25.1.0"

cache:
  directories:
    - _build
    - deps
