name: build

# Define workflow that runs when changes are pushed to the
# `main` branch or pushed to a PR branch that targets the `main`
# branch. Change the branch name if your project uses a
# different name for the main branch like "master" or "production".
on:
  push:
    branches: ["actions"] # adapt branch for project
  pull_request:
    branches: ["actions"] # adapt branch for project

# Sets the ENV `MIX_ENV` to `test` for running tests
env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      # Specify the OTP and Elixir versions to use when building
      # and running the workflow steps.
      matrix:
        otp: ["22.x", "23.x", "24.x", "25.x", "26.x"]
        elixir: ["1.9.x", "1.10.x", "1.11.x", "1.12.x", "1.14.x", "1.16.x"]
        include:
          - otp: "22.x"
            elixir: "1.9.x"
          - otp: "22.x"
            elixir: "1.10.x"
          - otp: "23.x"
            elixir: "1.10.x"
          - otp: "23.x"
            elixir: "1.11.x"
          - otp: "24.x"
            elixir: "1.12.x"
          - otp: "25.x"
            elixir: "1.14.x"
          - otp: "26.x"
            elixir: "1.16.x"

    steps:
      # Step: Setup Elixir + Erlang image as the base.
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      # Step: Check out the code.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Define how to cache deps. Restores existing cache if present.
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{runner.os}}-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-mix-${{env.cache-name}}-${{hashFiles('**/mix.lock')}}
          restore-keys: |
            ${{runner.os}}-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-mix-${{env.cache-name}}-

      # Step: Define how to cache the `_build` directory. After the first run,
      # this speeds up tests runs a lot. This includes not re-compiling our
      # project's downloaded deps every run.
      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{runner.os}}-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-mix-${{env.cache-name}}-${{hashFiles('**/mix.lock')}}
          restore-keys: |
            ${{runner.os}}-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-mix-${{env.cache-name}}-

      # Step: Cache Dialyzer PLTs.
      - name: Cache Dialyzer PLTs
        id: cache-plts
        uses: actions/cache@v3
        env:
          cache-name: cache-plts
        with:
          path: priv/plts
          key: ${{runner.os}}-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-mix-${{env.cache-name}}

      # Step: Download project dependencies. If unchanged, uses
      # the cached version.
      - name: Install dependencies
        run: mix deps.get

      - name: Check unused dependencies
        run: mix deps.unlock --check-unused

      - name: Audit dependencies
        run: mix deps.audit

      - name: Audit Hex packages
        run: mix hex.audit

      - name: Compiles without warnings
        run: mix compile --warnings-as-errors

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Static Code Analysis with Credo
        run: mix credo

      - name: Check typespecs with Dialyzer
        run: mix dialyzer --format github

      - name: Run tests
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
